version: '3'

services:
  django:
    build: ./app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
  frontend:
    build: ./ui
    command: ["npm", "start"]
    ports:
      - "8080:8080"